from __future__ import annotations

from . import (
    alerts,
    backtest,
    chart,
    keys,
    logs,
    market,
    ml,
    performance,
    pro_ai,
    settings,
    signals,
    sources,
    status,
    streams,
    system,
    trading,
    updates,
)

ALL_ROUTERS = [
    status.router,
    settings.router,
    keys.router,
    sources.router,
    logs.router,
    system.router,
    trading.router,
    signals.router,
    market.router,
    chart.router,
    streams.router,
    alerts.router,
    performance.router,
    backtest.router,
    ml.router,
    pro_ai.router,
    updates.router,
]
